module fluorescence

manifest morphine_enzyme

manifest urine_sample
manifest morphine_conjugate
manifest distilled_water
manifest tmb_substrate
manifest morphine_enzyme
manifest stop_reagent

instructions:

a = mix 20uL of urine_sample with morphine_enzyme
b = mix 100uL of morphine_conjugate with morphine_enzyme for 60s
heat b at 23c for 60m

repeat 6 times {
    b = mix 350uL of distilled_water with morphine_enzyme for 45s
    dispose b
}

cc = mix 100uL of tmb_substrate with morphine_enzyme
heat cc at 23c for 30m
d = mix cc with 100uL of stop_reagent for 60s

urine_reading = detect fluorescence on d for 30m
dispose d