module fluorescence

manifest heroin_enzyme
manifest oxycodone_enzyme

manifest oxycodone_conjugate
manifest urine_sample
manifest tmb_substrate
manifest distilled_water
manifest stop_reagent

instructions:

a = mix 20uL of urine_sample with oxycodone_enzyme
a = mix 100uL of oxycodone_conjugate with a for 60s
heat a at 23c for 60m
dispose a

repeat 6 times {
    a = mix 350uL of distilled_water with oxycodone_enzyme for 45s
    dispose a
}

b = mix 100uL of tmb_substrate with oxycodone_enzyme
heat b at 23c for 30m
b = mix 100uL of stop_reagent with b for 60s

urine_reading = detect fluorescence on oxycodone_enzyme for 30m
dispose b