manifest aaa
functions:
function bar(dd) {
    e = dispense aaa
    f = mix e with dd
    return f
}

function foo(aa) {
    g = dispense aaa
    h = bar(g)
    c = mix aa with h
    return c
}

function rue(bb) {
    k = dispense aaa
    l = foo(k)
    v = mix bb with l
    return v
}

instructions:
a = dispense aaa
b = foo(a)
dispose b
z = dispense aaa
y = rue(z)
dispose y
x = dispense aaa
u = foo(x)
dispose u
