// imports
import bar from bar
/* bar is defined as:
 * function bar(C, D) {
 *    ab = mix C with D
 *    x = detect weight on ab
 *    if (x <= 0.5) {
 *        heat ab at 10c
 *    }
 *    return ab
 * }
 */

// substances
module weight
manifest A
manifest B

functions:
function foo(x) {
    b = dispense B       // foo_0
    heat x at 10c
    heat b at 10c
    Y = bar(x, b)
    heat Y at 10c        // foo_1
    Y = split Y into 2
    drain Y[0]
    return Y[1]
}

instructions:
a = dispense A
bb = dispense B
heat a at 10c
heat bb at 10c // live across foo, can go to either if or after if
a = foo(a)          // FC block
if (9 < 10) {
    b = dispense B        // true block
    a = mix a with b
}    // no false block
heat a at 10c    // after true block
heat bb at 10c
dispose a
dispose bb
