// imports
import bar from my_lib
/* bar is defined as:
 * function bar(C, D) {
 *    ab = mix C with D for 2s
 *    x = detect weight on ab for 1s
 *    if (x <= 0.5) {
 *        heat ab at 10c for 1s
 *    }
 *    return ab
 * }
 */

// substances
module weight
manifest A
manifest B

functions:
function foo(x) {
    b = dispense B
    heat x at 10c for 2s
    heat b at 10c for 2s
    Y = bar(x, b)
    heat Y at 10c for 1s
    Y = split Y into 2
    drain Y[0]
    return Y[1]
}

instructions:
a = dispense A
bb = dispense B
heat a at 10c for 1s
heat bb at 10c for 1s // live across call to foo
a = foo(a)
if (9 < 10) {
    b = dispense B
    a = mix a with b for 2s
}
heat a at 10c for 1s
heat bb at 10c for 1s
dispose a
dispose bb
