// protein dilution assay derived from [Su and Chakrabarty, 2008]
// we assume volatility of all new mixed constituents, which must be used immediately.
module sensor
manifest Plasma
manifest Serum
manifest Glucose
manifest Lactate

instructions:
@usein 0s
mix1 = mix 10 units of Plasma with 10 units of Glucose for 5s
det1 = detect sensor on mix1 for 5s
dispose mix1

@usein 0s
mix2 = mix 10 units of Plasma with 10 units of Lactate for 5s
det2 = detect sensor on mix2 for 5s
dispose mix2

@usein 0s
mix3 = mix 10 units of Serum with 10 units of Glucose for 5s
det3 = detect sensor on mix3 for 5s
dispose mix3

@usein 0s
mix4 = mix 10 units of Serum with 10 units of Lactate for 5s
det4 = detect sensor on mix4 for 5s
dispose mix4
