//basic thermocycling pcr assay
//pcr master is sensitive to temperature -- assume no time for storing droplets, and fluorescence can be bleached out
module fluorescence
manifest template
manifest pcr_master
manifest forward_primer
manifest reverse_primer

instructions:
@usein 0s
pcr_mix = mix 10 units of pcr_master with 10 units of template for 5s

/* warm up pcr_mix */
@usein 0s
heat pcr_mix at 95c for 5s

@usein 0s
primer_mix = mix 10 units of forward_primer with 10 units of reverse_primer for 5s

@usein 0s
sample = mix pcr_mix with primer_mix for 5s

@usein 0s
heat sample at 53c for 15s
@usein 0s
heat sample at 72c for 10s
    @usein 0s
    heat sample at 53c for 15s
    @usein 0s
    heat sample at 72c for 10s
        @usein 0s
    heat sample at 53c for 15s
    @usein 0s
    heat sample at 72c for 10s
        @usein 0s
    heat sample at 53c for 15s
    @usein 0s
    heat sample at 72c for 10s
    @usein 0s
heat sample at 53c for 15s
@usein 0s
heat sample at 72c for 10s
    @usein 0s
    heat sample at 53c for 15s
    @usein 0s
    heat sample at 72c for 10s
        @usein 0s
    heat sample at 53c for 15s
    @usein 0s
    heat sample at 72c for 10s
        @usein 0s
    heat sample at 53c for 15s
    @usein 0s
    heat sample at 72c for 10s
        @usein 0s
    heat sample at 53c for 15s
    @usein 0s
    heat sample at 72c for 10s
    @usein 0s
heat sample at 53c for 15s
@usein 0s
heat sample at 72c for 10s
    @usein 0s
    heat sample at 53c for 15s
    @usein 0s
    heat sample at 72c for 10s
        @usein 0s
    heat sample at 53c for 15s
    @usein 0s
    heat sample at 72c for 10s
        @usein 0s
    heat sample at 53c for 15s
    @usein 0s
    heat sample at 72c for 10s
        @usein 0s
    heat sample at 53c for 15s
    @usein 0s
    heat sample at 72c for 10s
    @usein 0s
heat sample at 53c for 15s
@usein 0s
heat sample at 72c for 10s
    @usein 0s
    heat sample at 53c for 15s
    @usein 0s
    heat sample at 72c for 10s
        @usein 0s
    heat sample at 53c for 15s
    @usein 0s
    heat sample at 72c for 10s
        @usein 0s
    heat sample at 53c for 15s
    @usein 0s
    heat sample at 72c for 10s
        @usein 0s
    heat sample at 53c for 15s
    @usein 0s
    heat sample at 72c for 10s


x = detect fluorescence on sample for 3m

dispose sample