// protein dilution assay derived from [Su and Chakrabarty, 2008]
// we assume volatility of all new mixed constituents, which must be used immediately.
module sensor
manifest DsS //sample
manifest DsB //buffer
manifest DsR //reagent

instructions:
@usein 0s
mix1 = mix 10 units of DsS with 10 units of DsB for 3s
slt1 = split mix1 into 2

@usein 0s
mix2 = mix slt1[0] with 10 units of DsB for 3s
slt2 = split mix2 into 2

@usein 0s
mix3 = mix slt1[1] with 10 units of DsB for 3s
slt3 = split mix3 into 2

@usein 0s
mix4 = mix slt2[0] with 10 units of DsB for 3s
slt4 = split mix4 into 2

@usein 0s
mix5 = mix slt2[1] with 10 units of DsB for 3s
slt5 = split mix5 into 2

@usein 0s
mix6 = mix slt3[0] with 10 units of DsB for 3s
slt6 = split mix6 into 2

@usein 0s
mix7 = mix slt3[1] with 10 units of DsB for 3s
slt7 = split mix7 into 2

// first path
@usein 0s
mix8 = mix slt4[0] with 10 units of DsB for 3s
@usein 0s
mix9 = mix mix8 with 10 units of DsB for 3s
@usein 0s
mix10 = mix mix9 with 10 units of DsB for 3s
@usein 0s
mix11 = mix mix10 with 10 units of DsB for 3s
@usein 0s
mix12 = mix mix11 with 10 units of DsR for 3s
det1 = detect sensor on mix12 for 30s
dispose mix12

// second path
@usein 0s
mix13 = mix slt4[1] with 10 units of DsB for 3s
@usein 0s
mix14 = mix mix13 with 10 units of DsB for 3s
@usein 0s
mix15 = mix mix14 with 10 units of DsB for 3s
@usein 0s
mix16 = mix mix15 with 10 units of DsB for 3s
@usein 0s
mix17 = mix mix16 with 10 units of DsR for 3s
det2 = detect sensor on mix17 for 30s
dispose mix17

// third path
@usein 0s
mix18 = mix slt5[0] with 10 units of DsB for 3s
@usein 0s
mix19 = mix mix18 with 10 units of DsB for 3s
@usein 0s
mix20 = mix mix19 with 10 units of DsB for 3s
@usein 0s
mix21 = mix mix20 with 10 units of DsB for 3s
@usein 0s
mix22 = mix mix21 with 10 units of DsR for 3s
det3 = detect sensor on mix22 for 30s
dispose mix22

// fourth path
@usein 0s
mix23 = mix slt5[1] with 10 units of DsB for 3s
@usein 0s
mix24 = mix mix23 with 10 units of DsB for 3s
@usein 0s
mix25 = mix mix24 with 10 units of DsB for 3s
@usein 0s
mix26 = mix mix25 with 10 units of DsB for 3s
@usein 0s
mix27 = mix mix26 with 10 units of DsR for 3s
det4 = detect sensor on mix27 for 30s
dispose mix27

// fifth path
@usein 0s
mix28 = mix slt6[0] with 10 units of DsB for 3s
@usein 0s
mix29 = mix mix28 with 10 units of DsB for 3s
@usein 0s
mix30 = mix mix29 with 10 units of DsB for 3s
@usein 0s
mix31 = mix mix30 with 10 units of DsB for 3s
@usein 0s
mix32 = mix mix31 with 10 units of DsR for 3s
det5 = detect sensor on mix32 for 30s
dispose mix32

// sixth path
@usein 0s
mix33 = mix slt6[1] with 10 units of DsB for 3s
@usein 0s
mix34 = mix mix33 with 10 units of DsB for 3s
@usein 0s
mix35 = mix mix34 with 10 units of DsB for 3s
@usein 0s
mix36 = mix mix35 with 10 units of DsB for 3s
@usein 0s
mix37 = mix mix36 with 10 units of DsR for 3s
det6 = detect sensor on mix37 for 30s
dispose mix37

// seventh path
@usein 0s
mix38 = mix slt7[0] with 10 units of DsB for 3s
@usein 0s
mix39 = mix mix38 with 10 units of DsB for 3s
@usein 0s
mix40 = mix mix39 with 10 units of DsB for 3s
@usein 0s
mix41 = mix mix40 with 10 units of DsB for 3s
@usein 0s
mix42 = mix mix41 with 10 units of DsR for 3s
det7 = detect sensor on mix42 for 30s
dispose mix42

// eight path
@usein 0s
mix43 = mix slt7[1] with 10 units of DsB for 3s
@usein 0s
mix44 = mix mix43 with 10 units of DsB for 3s
@usein 0s
mix45 = mix mix44 with 10 units of DsB for 3s
@usein 0s
mix46 = mix mix45 with 10 units of DsB for 3s
@usein 0s
mix47 = mix mix46 with 10 units of DsR for 3s
det8 = detect sensor on mix47 for 30s
dispose mix47