// usein within 1s of the constraint time window

manifest droplet_a
manifest droplet_b
manifest droplet_c
manifest droplet_d

instructions:

a = dispense 10 units of droplet_a
b = dispense 10 units of droplet_b
c = dispense 10 units of droplet_c
d = dispense 10 units of droplet_d

@usein 21s
ab = mix a with b for 10s

@usein 21s
cd = mix c with d for 20s

@usein 11s
heat ab at 90c for 20s

heat cd at 90c for 10s

abcd = mix ab with cd

dispose abcd
