// create a lot of useins at the same time, mix and heat instructions
// time window constraints are correct in the code, no missed windows

manifest droplet_a
manifest droplet_b
manifest droplet_c
manifest droplet_d
manifest droplet_e
manifest droplet_f

instructions:

a = dispense 2 units of droplet_a
b = dispense 2 units of droplet_b
c = dispense 2 units of droplet_c
d = dispense 2 units of droplet_d
e = dispense 2 units of droplet_e
f = dispense 2 units of droplet_f

@usein 1m
ab = mix a with b for 10s

@usein 1m
heat ab at 90c for 10s

@usein 1m
cd = mix c with d for 10s

@usein 1m
heat cd at 90c for 10s

@usein 1m
ef = mix e with f for 10s

@usein 1m
heat ef at 90c for 10s

abcd = mix ab with cd for 10s

abcdef = mix abcd with ef for 10s

dispose abcdef