manifest a
manifest b
manifest c
manifest d
manifest e
manifest f

instructions:

@usein(finish) 10s
tab = mix 2 units of a with 2 units of b
ab = split tab into 4

@usein(start) 0s
heat ab[0] at 10c for 10s

@usein(start) 2s
abc = mix ab[1] with 1 units of c for 10s

@usein(finish) 5s
abc = mix abc with ab[0] for 10s

@usein(start) 10s
abd = mix ab[2] with 1 units of d for 4s

@usein(finish) 14s
abe = mix ab[3] with 1 units of e for 10s

tf = dispense 1 units of f

@usein(start) 20s
heat tf at 10c for 10s

@usein(finish) 10s
abcd = mix abc with abd for 5s

@usein(start) 10s
abef = mix abe with tf for 10s

abcdef = mix abcd with abef for 5s

dispose abcdef