module fluorescence
manifest PCRMix

instructions:
z = dispense 20 units of PCRMix
a = dispense 10 units of PCRMix
b = split z into 2
c = dispense 30 units of PCRMix
d = dispense 5 units of PCRMix

heat d at 94c for 2m

DNA_Sensor = detect fluorescence on d for 30s

if (DNA_Sensor <= 80) {
    e = mix 5 units of a with 5 units of b[0]  // == 10
}
else {
    e = mix 3 units of b[1] with 15 units of c //== 18
}

dispose d
dispose e
