module mod
stationary stat
manifest aaa
manifest bbb
manifest ccc
manifest ddd

functions:

function foo(a, b) {
    c = mix a with b
    return c
}

instructions:

if (3 < 3) {
    if (5 < 2) {
        if (3 == 2) {
            if (3 == 3) {

            } else {
                if (3 < 3) {

                }
            }
        }
    } else {

    }
} else {
    if (3 > 3) {

    } else {

    }
}
