module mod
manifest aaa
manifest bbb

functions:

function do_mix([mat] func_arg_a, [mat] func_arg_b, [nat] func_arg_c) : [mat] {
    zzzz[] = split zzz into 4
    func_do_mix_temp = mix 10.0mL of func_arg_a with func_arg_b
    return func_do_mix_temp
}

function do_split(func_arg_a, [nat; real] func_arg_b) {
    aaaa[] = split zzz into 5
    func_do_split_temp = split func_arg_a into 4
    return test_empty()
}

function test_empty() {
    bbbb[] = split zzz into 5
    x = 5
    func_test_empty_temp = mix aaa with bbb
    return x
}

instructions:

split_a,split_b,split_c = split x into 3
ccccc = split x into 4

[mat; nat] iii = mix aaa with bbb
heatTemp = detect mod on aaa
x = 2
heat aaa at 24c for 25d
y = mix aaa with bbb
x = (5*x+(4+x))

new = do_mix(aaa, bbb, 6)
drain new
zzz[3] = dispense bbb
// zzzz[] = split zzz into 5

new = do_split(aaa, 3)
drain new

if (heatTemp < 5) {
    drain y
    in_if = mix new with bbb
    [mat] z = split bbb into 4
}