manifest aaa
manifest bbb
manifest ccc
manifest ddd
manifest eee
manifest fff
manifest ggg
manifest hhh



instructions:

m1 = dispense aaa
m2 = dispense bbb
m3 = dispense ccc
m4 = dispense ddd
m5 = dispense eee
m6 = dispense fff
m7 = dispense ggg
m8 = dispense hhh

f1 = mix m1 with m2
f2 = mix m3 with m4
f3 = mix m5 with m6
f4 = mix m7 with m8

t1 = mix f1 with f2
t2 = mix f3 with f4

final = mix t1 with t2

dispose final