module fluorescence

manifest Anti_Morphine
manifest Anti_Oxy
manifest Anti_Fentanyl
manifest Anti_Ciprofloxcin
manifest Anti_Heroin
manifest UrineSample

instructions:

us1 = dispense 10 units of UrineSample
us2 = dispense 10 units of UrineSample
us3 = dispense 10 units of UrineSample
us4 = dispense 10 units of UrineSample
us5 = dispense 10 units of UrineSample

aa = dispense 10 units of Anti_Morphine
a = mix us1 with aa
bb = dispense 10 units of Anti_Oxy
b = mix us2 with bb
cc = dispense 10 units of Anti_Fentanyl
c = mix us3  with cc
dd = dispense 10 units of Anti_Ciprofloxcin
d = mix us4 with dd
ee = dispense 10 units of Anti_Heroin
e = mix us5 with ee

MorphineReading = detect fluorescence on a for 5s
OxyReading = detect fluorescence on b for 5s
FentanylReading = detect fluorescence on c for 5s
CiproReading = detect fluorescence on d for 5s
HeroinReading = detect fluorescence on e for 5s

dispose a
dispose b
dispose c
dispose d
dispose e