module fluorescence

manifest antigen

manifest urine_sample
manifest fentanyl_conjugate
manifest tmb_substrate
manifest distilled_water
manifest stop_reagent

instructions:

aa = dispense 20 units of urine_sample
aaa = dispense antigen
a = mix aa with aaa
bb = dispense 100 units of fentanyl_conjugate
b = mix bb with a for 60s
heat b at 23c for 60m
dispose b

repeat 6 times {
    zz = dispense 350 units of distilled_water
    z = mix zz with a for 45s
    dispose z
}

aaaa = dispense 100 units of tmb_substrate
a = mix aaaa with a
heat a at 23c for 30m

aaaaa = dispense 100 units of stop_reagent
a = mix a with aaaaa for 60s
negative_reading = detect fluorescence on a for 30m
dispose a