module fluorescence

manifest Antigen1
manifest Antigen2
manifest Antigen3

manifest morphine_conjugate
manifest negative_standard
manifest diluted_sample
manifest positive_standard
manifest distilled_water
manifest tmb_substrate
manifest stop_reagent

instructions:
d = dispense 20 units of negative_standard
e = dispense Antigen1
a = mix d with e
f = dispense 20 units of positive_standard
g = dispense Antigen2
b = mix f with g
h = dispense 20 units of diluted_sample
i = dispense Antigen3
cc = mix h with i

dd = dispense 100 units of morphine_conjugate
a = mix dd with a for 60s
ff = dispense 100 units of morphine_conjugate
b = mix ff with b for 60s
hh = dispense 100 units of morphine_conjugate
cc = mix hh with cc for 60s

heat a at 23c for 60m
heat b at 23c for 60m
heat cc at 23c for 60m

dispose a
dispose b
dispose cc

repeat 6 times {
    j = dispense 350 units of distilled_water
    k = dispense Antigen1
    aa = mix j with k for 45s
    l = dispense 350 units of distilled_water
    m = dispense Antigen2
    bb = mix l with m for 45s
    n = dispense 350 units of distilled_water
    o = dispense Antigen3
    cc = mix n with o for 45s

    dispose aa
    dispose bb
    dispose cc
}

jj = dispense 100 units of tmb_substrate
kk = dispense Antigen1
aa = mix jj with kk
ll = dispense 100 units of tmb_substrate
mm = dispense Antigen2
bb = mix ll with mm
nn = dispense 100 units of tmb_substrate
oo = dispense Antigen3
cc = mix nn with oo

heat aa at 23c for 30m
heat bb at 23c for 30m
heat cc at 23c for 30m

p = dispense stop_reagent
aa = mix p with 100 units of aa for 60s
q = dispense stop_reagent
bb = mix q with 100 units of bb for 60s
r = dispense stop_reagent
cc = mix r with 100 units of cc for 60s

negative_reading = detect fluorescence on aa for 30m
positive_reading = detect fluorescence on bb for 30m
sample_reading = detect fluorescence on cc for 30m

dispose aa
dispose bb
dispose cc