module fluorescence

manifest reagent
manifest glucose
manifest distilled_water
manifest Sample

instructions:

aa = dispense 10 units of glucose
bb = dispense 10 units of reagent
result1 = mix aa with bb for 10s
reading1 = detect fluorescence on result1 for 30s
aaa = dispense 10 units of distilled_water
bbb = dispense 10 units of reagent
a = mix aaa with bbb for 30s
dispose a

cc = dispense 10 units of glucose
dd = dispense 20 units of reagent
result2 = mix cc with dd for 10s
reading2 = detect fluorescence on result2 for 30s
ccc = dispense 10 units of distilled_water
ddd = dispense 10 units of reagent
a = mix ccc with ddd for 30s
dispose a

ee = dispense 10 units of glucose
ff = dispense 40 units of reagent
result3 = mix ee with ff for 10s
reading3 = detect fluorescence on result3 for 30s
eee = dispense 10 units of distilled_water
fff = dispense 10 units of reagent
a = mix eee with fff for 30s
dispose a

gg = dispense 10 units of glucose
hh = dispense 80 units of reagent
result4 = mix gg with hh for 10s
reading4 = detect fluorescence on result4 for 30s
ggg = dispense 10 units of distilled_water
hhh = dispense 10 units of reagent
a = mix ggg with hhh for 30s
dispose a

ii = dispense 10 units of glucose
jj = dispense 10 units of reagent
result5 = mix ii with jj for 10s
reading5 = detect fluorescence on result5 for 30s
iii = dispense 10 units of distilled_water
jjj = dispense 10 units of reagent
a = mix iii with jjj for 30s

dispose a
dispose result1
dispose result2
dispose result3
dispose result4
dispose result5