module fluorescence

manifest heroin_enzyme
manifest heroin_conjugate
manifest urine_sample
manifest tmb_substrate
manifest distilled_water
manifest stop_reagent

instructions:

d = dispense 20 units of urine_sample
e = dispense 1 units of heroin_enzyme
a = mix d with e for 10s
f = dispense 100 units of heroin_conjugate
a = mix f with a for 60s
heat a at 23c for 60m
dispose a

repeat 6 times {
    g = dispense 350 units of distilled_water
    h = dispense heroin_enzyme
    b = mix g with h for 45s
    dispose b
}
i = dispense 100 units of tmb_substrate
j = dispense heroin_enzyme
cc = mix i with j
heat cc at 23c for 30m
k = dispense 100 units of stop_reagent
cc = mix k with 100 units of cc for 60s

urine_reading = detect fluorescence on cc for 30m
dispose cc