module fluorescence

manifest morphine_enzyme

manifest urine_sample
manifest morphine_conjugate
manifest distilled_water
manifest tmb_substrate
manifest morphine_enzyme
manifest stop_reagent

instructions:

e = dispense 20 units of urine_sample
f = dispense morphine_enzyme
a = mix e with f
g = dispense 100 units of morphine_conjugate
h = dispense morphine_enzyme
b = mix g with h for 60s
heat b at 23c for 60m
dispose a
dispose b

repeat 6 times {
    i = dispense 350 units of distilled_water
    j = dispense morphine_enzyme
    b = mix i with j for 45s
    dispose b
}

k = dispense 100 units of tmb_substrate
l = dispense morphine_enzyme
cc = mix k with l
heat cc at 23c for 30m
m = dispense 100 units of stop_reagent
d = mix cc with m for 60s

urine_reading = detect fluorescence on d for 30m
dispose d