module fluorescence

manifest heroin_enzyme
manifest oxycodone_enzyme

manifest oxycodone_conjugate
manifest urine_sample
manifest tmb_substrate
manifest distilled_water
manifest stop_reagent

instructions:

c = dispense 20 units of urine_sample
d = dispense oxycodone_enzyme
a = mix c with d
e = dispense 100 units of oxycodone_conjugate
a = mix e with a for 60s
heat a at 23c for 60m
dispose a

repeat 6 times {
    f = dispense 350 units of distilled_water
    g = dispense 100 units of oxycodone_enzyme
    a = mix f with g for 45s
    dispose a
}

h = dispense 100 units of tmb_substrate
i = dispense oxycodone_enzyme
b = mix h with i
heat b at 23c for 30m
j = dispense 100 units of stop_reagent
b = mix j with b for 60s

urine_reading = detect fluorescence on b for 30m
dispose b