module weight
manifest PCRMasterMix
manifest Template

instructions:

a = dispense 50 units of PCRMasterMix
b = dispense 50 units of Template
PCRMix = mix a with b for 1s

repeat 5 times {
    heat PCRMix at 95c for 20s
    volumeWeight = detect weight on PCRMix

    if (volumeWeight <= 50) {
        c = dispense 25 units of PCRMasterMix
        d = dispense 25 units of Template
        replacement = mix c with d for 5s
        heat replacement at 95c for 45s
        PCRMix = mix PCRMix with replacement for 5s
    }

    heat PCRMix at 68c for 30s
    heat PCRMix at 95c for 45s
}

heat PCRMix at 68c for 5m
dispose PCRMix