manifest aa
manifest bb
manifest cc
manifest dd
manifest ee

instructions:

a = dispense aa
b = dispense bb
c = dispense cc
d = dispense dd
e = dispense ee

@usein 10s
heat a at 100c for 50s

@usein 10s
heat b at 100c for 40s

@usein 10s
heat c at 100c for 30s

@usein 10s
heat d at 100c for 20s

@usein 10s
heat e at 100c for 10s

/////////////////////////

@usein 10s
ab = mix a with b for 10s

@usein 10s
heat ab at 100c for 10s

@usein 10s
abc = mix ab with c for 10s

@usein 10s
heat abc at 100c for 10s

@usein 10s
abcd = mix abc with d for 10s

@usein 10s
heat abcd at 100c for 10s

@usein 10s
abcde = mix abcd with e for 10s

dispose abcde