manifest aa
manifest bb
manifest cc
manifest dd
manifest ee
manifest ff
manifest gg
manifest hh

instructions:

a = dispense aa
b = dispense bb
c = dispense cc
d = dispense dd
e = dispense ee
f = dispense ff
g = dispense gg
h = dispense hh

@usein 10s
heat a at 100c for 10s

@usein 10s
heat b at 100c for 10s

@usein 10s
heat c at 100c for 10s

@usein 10s
heat d at 100c for 10s

@usein 10s
heat e at 100c for 10s

@usein 10s
heat f at 100c for 10s

@usein 10s
heat g at 100c for 10s

@usein 10s
heat h at 100c for 10s

/////////////////////////

ab = mix a with b for 10s
heat ab at 100c for 10s

abc = mix ab with c for 10s
heat abc at 100c for 10s

abcd = mix abc with d for 10s
heat abcd at 100c for 10s

abcde = mix abcd with e for 10s
heat abcde at 100c for 10s

abcdef = mix abcde with f for 10s
heat abcdef at 100c for 10s

abcdefg = mix abcdef with g for 10s
heat abcdefg at 100c for 10s

abcdefgh = mix abcdefg with h for 10s

dispose abcdefgh